# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'stack-question' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.8.2'
  # Pods for stack-question

  target 'stack-questionTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
